### ISSUE TITLE
Why we need raw 'ADD' opcode?

### ISSUE THREAD

**Issue by rick-200** [tekknolagi/icdemo#2]
I mean, if we assume that most 'ADD' opcode will be applied on int operand,
you can add 'do_add_int()' or something to cache, and replace all 'ADD' with 'ADD_INT' at once,
then if observed non-int operand, turn 'ADD_INT' to 'ADD_CACHED'.
Isn't that quicker?

After all, after first 'ADD' opcode, cache won't be empty, then other 'ADD' are meaningless, so we can just make cache filled before executing the bytecode.

**Comment by tekknolagi** [comment]
I don't know if I have a great response for you, but it feels weird to me to make that assumption so explicit that I emit integer addition for all of my bytecode. I think I'd rather the runtime do the type discovery for me. Good question!

**Comment by rick-200** [comment]
I see. Actually I came from your blog , that's why I had such assumption. It helped me a lot.
